# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetchw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('elmail', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dummyquery',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetchw.DummyUser'),
        ),
    ]
