# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetchw', '0002_auto_20170730_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyquery',
            name='uid',
        ),
        migrations.DeleteModel(
            name='TestWeather',
        ),
        migrations.DeleteModel(
            name='DummyQuery',
        ),
        migrations.DeleteModel(
            name='DummyUser',
        ),
    ]
